"""set default value to enum

Revision ID: 6639f1e853ac
Revises: 74f0ee9616ff
Create Date: 2025-12-08 16:48:03.350513

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6639f1e853ac'
down_revision: Union[str, Sequence[str], None] = '74f0ee9616ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('USER', 'SUPER_ADMIN', name='userrole'),
               nullable=True)
    op.alter_column('userauthentication', 'authentication_status',
               existing_type=postgresql.ENUM('PENDING', 'EXPIRED', 'CANCELED', 'SUCCESS', name='authenticationstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userauthentication', 'authentication_status',
               existing_type=postgresql.ENUM('PENDING', 'EXPIRED', 'CANCELED', 'SUCCESS', name='authenticationstatus'),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('USER', 'SUPER_ADMIN', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###
