"""user profile authentication table

Revision ID: 75a7b3ed38ab
Revises: a2c85fe50c8a
Create Date: 2025-12-09 12:25:15.760630

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75a7b3ed38ab'
down_revision: Union[str, Sequence[str], None] = 'a2c85fe50c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'SUPER_ADMIN', name='userrole').create(op.get_bind())
    sa.Enum('PENDING', 'ACTIVE', 'DELETED', 'BLOCKED', name='accountstatus').create(op.get_bind())
    sa.Enum('PENDING', 'EXPIRED', 'CANCELED', 'SUCCESS', name='authenticationstatus').create(op.get_bind())
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('account_status', postgresql.ENUM('PENDING', 'ACTIVE', 'DELETED', 'BLOCKED', name='accountstatus', create_type=False), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'SUPER_ADMIN', name='userrole', create_type=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('userauthentication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authentication_status', postgresql.ENUM('PENDING', 'EXPIRED', 'CANCELED', 'SUCCESS', name='authenticationstatus', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprofile')
    op.drop_table('userauthentication')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    sa.Enum('PENDING', 'EXPIRED', 'CANCELED', 'SUCCESS', name='authenticationstatus').drop(op.get_bind())
    sa.Enum('PENDING', 'ACTIVE', 'DELETED', 'BLOCKED', name='accountstatus').drop(op.get_bind())
    sa.Enum('USER', 'SUPER_ADMIN', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
