"""add auth type in user autehntication table

Revision ID: 8f6c7d22cd2c
Revises: 0e14e6961fda
Create Date: 2025-12-10 10:20:09.358974

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f6c7d22cd2c'
down_revision: Union[str, Sequence[str], None] = '0e14e6961fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('email', 'password', name='authenticationtype').create(op.get_bind())
    op.add_column('userauthentication', sa.Column('authentication_type', postgresql.ENUM('email', 'password', name='authenticationtype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userauthentication', 'authentication_type')
    sa.Enum('email', 'password', name='authenticationtype').drop(op.get_bind())
    # ### end Alembic commands ###
