"""enough for today-10-12-25

Revision ID: 91a1495ca1dd
Revises: e406cf978f7f
Create Date: 2025-12-10 15:25:41.590994

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a1495ca1dd'
down_revision: Union[str, Sequence[str], None] = 'e406cf978f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'need_to_reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'need_to_reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
