"""add time field in user and user profile

Revision ID: bb97ce9b5a1e
Revises: c72a5ff66804
Create Date: 2025-12-09 15:38:42.010571

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb97ce9b5a1e'
down_revision: Union[str, Sequence[str], None] = 'c72a5ff66804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('userprofile', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('userprofile', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'updated_at')
    op.drop_column('userprofile', 'created_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
