"""add time field in user authentication

Revision ID: c72a5ff66804
Revises: fcf4f17d7f27
Create Date: 2025-12-09 15:30:52.361164

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72a5ff66804'
down_revision: Union[str, Sequence[str], None] = 'fcf4f17d7f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userauthentication', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('userauthentication', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userauthentication', 'updated_at')
    op.drop_column('userauthentication', 'created_at')
    # ### end Alembic commands ###
