"""create tables

Revision ID: d5bad42ad356
Revises: 
Create Date: 2025-12-11 13:40:38.649816

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5bad42ad356'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'SUPER_ADMIN', name='userrole').create(op.get_bind())
    sa.Enum('pending', 'active', 'deleted', 'blocked', name='accountstatus').create(op.get_bind())
    sa.Enum('email', 'password', name='authenticationtype').create(op.get_bind())
    sa.Enum('pending', 'expired', 'canceled', 'success', name='authenticationstatus').create(op.get_bind())
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('need_to_reset_password', sa.Boolean(), nullable=True),
    sa.Column('account_status', postgresql.ENUM('pending', 'active', 'deleted', 'blocked', name='accountstatus', create_type=False), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'SUPER_ADMIN', name='userrole', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('userauthentication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authentication_status', postgresql.ENUM('pending', 'expired', 'canceled', 'success', name='authenticationstatus', create_type=False), nullable=True),
    sa.Column('authentication_type', postgresql.ENUM('email', 'password', name='authenticationtype', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprofile')
    op.drop_table('userauthentication')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    sa.Enum('pending', 'expired', 'canceled', 'success', name='authenticationstatus').drop(op.get_bind())
    sa.Enum('email', 'password', name='authenticationtype').drop(op.get_bind())
    sa.Enum('pending', 'active', 'deleted', 'blocked', name='accountstatus').drop(op.get_bind())
    sa.Enum('USER', 'SUPER_ADMIN', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
