"""add need_t_reset_pass in user table

Revision ID: e406cf978f7f
Revises: 8f6c7d22cd2c
Create Date: 2025-12-10 10:57:13.375513

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e406cf978f7f'
down_revision: Union[str, Sequence[str], None] = '8f6c7d22cd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('need_to_reset_password', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'need_to_reset_password')
    # ### end Alembic commands ###
