"""set acccount status enum lower case

Revision ID: f89f424c0e9a
Revises: 75a7b3ed38ab
Create Date: 2025-12-09 12:30:18.633623

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'f89f424c0e9a'
down_revision: Union[str, Sequence[str], None] = '75a7b3ed38ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='accountstatus',
        new_values=['pending', 'active', 'deleted', 'blocked'],
        affected_columns=[TableReference(table_schema='public', table_name='user', column_name='account_status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='accountstatus',
        new_values=['PENDING', 'ACTIVE', 'DELETED', 'BLOCKED'],
        affected_columns=[TableReference(table_schema='public', table_name='user', column_name='account_status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
