"""set acccount status enum lower case

Revision ID: fcf4f17d7f27
Revises: f89f424c0e9a
Create Date: 2025-12-09 13:24:00.918895

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'fcf4f17d7f27'
down_revision: Union[str, Sequence[str], None] = 'f89f424c0e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='authenticationstatus',
        new_values=['pending', 'expired', 'canceled', 'success'],
        affected_columns=[TableReference(table_schema='public', table_name='userauthentication', column_name='authentication_status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='authenticationstatus',
        new_values=['PENDING', 'EXPIRED', 'CANCELED', 'SUCCESS'],
        affected_columns=[TableReference(table_schema='public', table_name='userauthentication', column_name='authentication_status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
